# ---
# name: "Scheduled/Manual terraform destroy"

# on:
#   workflow_dispatch:
#   schedule:
#   - cron: "0 18 * * 1-5" # Run the terraform destroy every workday at 18h UTC

# jobs:
#   terraform-manual-destroy:
#     runs-on: ubuntu-latest
#     env:
#       TF_ACTION_WORKING_DIR: .
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

#     steps:

#     - name: "Checkout the repository"
#       uses: actions/checkout@v3

#     - name: "Setup Terraform"
#       uses: hashicorp/setup-terraform@v2

#     - name: "Run terraform init"
#       id: init
#       run: "terraform init -no-color"
    
#     - name: "Delete some resources on the state file"
#       run: 'terraform state rm $(terraform-bin state list | grep "argocd_application\|argocd_project\|kubernetes_\|helm_")'
#       continue-on-error: true # This is to avoid failed workflows and the consequent noise when the scheduled destroy runs on the days we have not created the test deployment

#     - name: "Run terraform destroy"
#       run: "terraform destroy -no-color -auto-approve -input=false"
