# ---
# name: "Manual terraform apply"

# on:
#   workflow_dispatch:

# jobs:
#   terraform-manual-apply:
#     runs-on: ubuntu-latest
#     env:
#       TF_ACTION_WORKING_DIR: .
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

#     steps:

#     - name: "Checkout the repository"
#       uses: actions/checkout@v3

#     - name: "Setup Terraform"
#       uses: hashicorp/setup-terraform@v2

#     - name: "Run terraform init"
#       id: init
#       run: "terraform init -no-color"
    
#     - name: "Run terraform validate"
#       id: validate
#       run: "terraform validate -no-color"

#     - name: "Run terraform plan"
#       id: plan
#       run: "terraform plan -no-color -input=false -out tfplan"

#     - name: "Run terraform apply"
#       run: "terraform apply -no-color -auto-approve -input=false tfplan"
